{
  "MODE": {
    "name": "SALGL-R101"
  },
  "DATA": {
    "dataset_dir": "/media/data2/MLICdataset/",
    "dataname": "coco14",
    "num_workers": 8,
    "num_class": 80,
    "len_train_loader": -1,
    "prob": 0.5,
    "classnames": [
      "person",
      "bicycle",
      "car",
      "motorcycle",
      "airplane",
      "bus",
      "train",
      "truck",
      "boat",
      "traffic light",
      "fire hydrant",
      "stop sign",
      "parking meter",
      "bench",
      "bird",
      "cat",
      "dog",
      "horse",
      "sheep",
      "cow",
      "elephant",
      "bear",
      "zebra",
      "giraffe",
      "backpack",
      "umbrella",
      "handbag",
      "tie",
      "suitcase",
      "frisbee",
      "skis",
      "snowboard",
      "sports ball",
      "kite",
      "baseball bat",
      "baseball glove",
      "skateboard",
      "surfboard",
      "tennis racket",
      "bottle",
      "wine glass",
      "cup",
      "fork",
      "knife",
      "spoon",
      "bowl",
      "banana",
      "apple",
      "sandwich",
      "orange",
      "broccoli",
      "carrot",
      "hot dog",
      "pizza",
      "donut",
      "cake",
      "chair",
      "couch",
      "potted plant",
      "bed",
      "dining table",
      "toilet",
      "tv",
      "laptop",
      "mouse",
      "remote",
      "keyboard",
      "cell phone",
      "microwave",
      "oven",
      "toaster",
      "sink",
      "refrigerator",
      "book",
      "clock",
      "vase",
      "scissors",
      "teddy bear",
      "hair drier",
      "toothbrush"
    ],
    "TRANSFORM": {
      "img_size": 448,
      "crop": false,
      "cutout": true,
      "length": 224,
      "cut_fact": 0.5,
      "orid_norm": false,
      "remove_norm": false,
      "n_holes": 1,
      "TWOTYPE": {
        "is_twotype": false,
        "img_size": 448,
        "min_scale": 0.08
      }
    }
  },
  "INPUT": {
    "SIZE": [
      448,
      448
    ],
    "INTERPOLATION": "bicubic",
    "TRANSFORMS": [
      "random_resized_crop",
      "MLC_Policy",
      "random_flip",
      "normalize"
    ],
    "NO_TRANSFORM": false,
    "PIXEL_MEAN": [
      0.48145466,
      0.4578275,
      0.40821073
    ],
    "PIXEL_STD": [
      0.26862954,
      0.26130258,
      0.27577711
    ],
    "CROP_PADDING": 4,
    "CUTOUT_N": 1,
    "CUTOUT_LEN": 16,
    "GN_MEAN": 0.0,
    "GN_STD": 0.15,
    "RANDAUGMENT_N": 2,
    "RANDAUGMENT_M": 10,
    "COLORJITTER_B": 0.4,
    "COLORJITTER_C": 0.4,
    "COLORJITTER_S": 0.4,
    "COLORJITTER_H": 0.1,
    "RGS_P": 0.2,
    "GB_P": 0.5,
    "GB_K": 21,
    "random_resized_crop_scale": [
      0.5,
      1.0
    ],
    "cutout_proportion": 0.4,
    "TRANSFORMS_TEST": [
      "resize",
      "normalize"
    ]
  },
  "MODEL": {
    "arch": "SALGL-R101",
    "use_BN": false,
    "BACKBONE": {
      "backbone": "resnet101",
      "pretrained": true,
      "frozen_backbone": false
    },
    "SALGL": {
      "embed_type": "bert",
      "num_scenes": 6,
      "soft": false,
      "topk": 3,
      "threshold": 0.5,
      "outmess": true,
      "num_steps": 3,
      "zero_init": false,
      "comat_ema": true,
      "normalize": true,
      "ignore_self": false,
      "pos": false,
      "lamda": 1.0,
      "pct_start": 0.2,
      "distributed": true,
      "embed_path": "data/mscoco/bert.npy",
      "comat_path": "data/mscoco/comatrix.npy",
      "ignore_path": "data/mscoco/ignore.npy"
    },
    "CLASSIFIER": {
      "num_class": 80
    },
    "CAPTION": {
      "n_ctx_pos": 16,
      "n_ctx_neg": 16,
      "csc": true,
      "ctx_init_pos": "",
      "ctx_init_neg": "",
      "class_token_position": "end",
      "gl_merge_rate": 0.5,
      "n_ctx": 16,
      "ctx_init": ""
    }
  },
  "LOSS": {
    "loss_dev": -1,
    "loss_mode": "asl",
    "ASL": {
      "eps": 1e-05,
      "dtgfl": true,
      "gamma_pos": 0.0,
      "gamma_neg": 2.0,
      "loss_clip": 0.0
    },
    "Coef": {
      "cls_asl_coef": 1.0,
      "sample_en_coef": 1.0,
      "batch_en_coef": 1.0
    }
  },
  "OPTIMIZER": {
    "optim": "AdamW",
    "lr_scheduler": "OneCycleLR",
    "pattern_parameters": "single_lr",
    "momentum": 0.9,
    "sgd_dampening": 0,
    "sgd_nesterov": false,
    "weight_decay": 0.01,
    "max_clip_grad_norm": 0,
    "epoch_step": [
      10,
      20
    ],
    "batch_size": 128,
    "lr": 0.0001,
    "lrp": 0.1,
    "lr_mult": 1.0,
    "warmup_scheduler": false,
    "warmup_type": "linear",
    "warmup_epoch": 0,
    "warmup_multiplier": 50,
    "warmup_lr": 1e-05
  },
  "DDP": {
    "world_size": 4,
    "rank": 0,
    "dist_url": "env://",
    "local_rank": 0,
    "gpus": 0,
    "seed": 42
  },
  "TRAIN": {
    "seed": 1,
    "amp": true,
    "early_stop": true,
    "kill_stop": true,
    "device": "cuda",
    "start_epoch": 0,
    "epochs": 80,
    "ema_decay": 0.9997,
    "ema_epoch": -1,
    "ratio": 1.0,
    "evaluate": false,
    "cpus": null
  },
  "INPUT_OUTPUT": {
    "output": "checkpoint/salgl/coco2014/work4/",
    "resume": "",
    "resume_omit": [],
    "print_freq": 400,
    "out_aps": false
  },
  "EVAL": {
    "val_interval": 1,
    "val_epoch_start": 0
  }
}